name: Build

on:
    workflow_dispatch:
    watch:
        types: [started]
    schedule:
        - cron: "0 */6 * * *"

jobs:
    check_release:
        runs-on: ubuntu-latest
        outputs:
            HAS_NEWER_VERSION: ${{ steps.check.outputs.HAS_NEWER_VERSION }}
            APP_LATEST_TAG: ${{ steps.check.outputs.APP_LATEST_TAG }}
        steps:
            - uses: actions/checkout@v2

            - name: check if release
              id: check
              shell: bash
              run: |
                  source $GITHUB_WORKSPACE/check.sh
                  echo "HAS_NEWER_VERSION=$HAS_NEWER_VERSION" >> "$GITHUB_OUTPUT"
                  echo "APP_LATEST_TAG=$APP_LATEST_TAG" >> "$GITHUB_OUTPUT"

    build_apk:
        needs: check_release
        if: github.event_name != 'schedule' || needs.check_release.outputs.HAS_NEWER_VERSION == 'TRUE'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                device: [main, v2]
                mode: [normal, lollipop]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Java JDK
              uses: actions/setup-java@v1.4.4
              with:
                  java-version: 17

            - name: build apk
              shell: bash
              run: cd $GITHUB_WORKSPACE; source $GITHUB_WORKSPACE/go.sh

            - name: upload artifact
              uses: actions/upload-artifact@v2
              if: success()
              with:
                  name: ${{ env.APP_OUTPUT_NAME }}
                  path: ${{ env.OUTPUT_PATH }}

    release:
        needs: [check_release,build_apk]
        if: github.event_name != 'schedule' || needs.check_release.outputs.HAS_NEWER_VERSION == 'TRUE'
        runs-on: ubuntu-latest
        env:
            OUTPUT_PATH: apk
            APP_LATEST_TAG: ${{ needs.check_release.outputs.APP_LATEST_TAG}}
        steps:
            - name: Download artifacts
              id: download
              uses: actions/download-artifact@v3
              with:
                  path: ${{env.OUTPUT_PATH}}/

            - name: update readme
              shell: bash
              run: cd $GITHUB_WORKSPACE; source $GITHUB_WORKSPACE/update.sh

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}

            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  body_path: ${{ env.APP_LATEST_BODY }}
                  tag_name: ${{ env.TAG_NAME }}
                  files: ${{ env.FILES }}
